# Network Policies
networkPolicies:
  enabled: false

# Istio
istiooperator:
  enabled: true
istio:
  enabled: true

# Gatekeeper
gatekeeper:
  enabled: false
clusterAuditor:
  enabled: false

# Logging
eckoperator:
  enabled: false
logging:
  enabled: false
fluentbit:
  enabled: false

# Monitoring
monitoring:
  enabled: false

# Other Tools
jaeger:
  enabled: false
kiali:
  enabled: false
twistlock:
  enabled: false

podinfo:
  enabled: true
  git:
    repo: https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/podinfo
    branch: bigbang
    path: chart
  flux: {}
  ingress:
    gateway: ""
