name: Mirror and Run Gitlab CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v1
       - name: Mirror + trigger CI
         uses: SvanBoxel/gitlab-mirror-and-ci-action@master
         with:
           args: "https://gitlab.com/<namespace>/<repository>"
         env:
           FORCE_PUSH: "false"
           GITLAB_HOSTNAME: "gitlab.com"
           GITLAB_USERNAME: "svboxel"
           GITLAB_PASSWORD: ${{ secrets.GITLAB_ACCESS_TOKEN }}
           GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
           GITHUB_TOKEN: ${{ secrets.GITLAB_ACCESS_TOKEN }}
